name: CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Zig
        run: sudo snap install zig --classic --beta
      - name: Install NPM and esbuild
        run: |
          sudo apt install nodejs
          npm install esbuild
      - name: Clone XTerm.js
        run: git clone https://github.com/xtermjs/xterm.js.git
      - name: ESBuild XTerm.js
        run: |
          cd xterm.js
          npm run esbuild
          cd ..
      - name: Move XTerm.js files
        run: mv xterm.js/css/xterm.css xterm.js/lib/* zig-out/bin
      - name: Zig Build
        run: zig build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: zig-out/bin/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
